language: python
addons:
  apt:
    packages:
     - libatlas-dev
     - liblapack-dev
     - gfortran
env:
  - DJANGO_VERSION=1.8.7
  - DJANGO_VERSION=1.9
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - "pip install Django==$DJANGO_VERSION"
  - "pip install ."
script: python setup.py test
sudo: false
